### ISSUE TITLE
Don't log private information by default

### ISSUE THREAD

**Issue by tulir** [tulir/mautrix-facebook#22]
Logs currently contain message content and other private information. The logs should be minimized to contain as little private information as possible without reducing usefulness when debugging.

**Comment by spantaleev** [comment]
Logs also seem to contain the `hs_token` value ("A unique token for Homeservers to use to authenticate requests to application services").

Since the application service is usually not exposed to the internet and only runs locally, it likely isn't that bad.. but it would be better to not log it anyway.

**Comment by emorrp1** [comment]
This includes users facebook passwords and access tokens, saved to disk! Hope everyone has two-factor turned on.

Alternatively, please include some recommended logging settings in "Production Setup" e.g. it wasn't sufficient for me to remove FILE from logging.root.handlers. I ended up with a brute force setting the logging.loggers.{mau,fbchat}.level to INFO, but that means if anything goes wrong, there's limited debug obviously.
