### ISSUE TITLE
requirements.txt missing dependencies

### ISSUE THREAD

**Issue by bobpaul** [tulir/mautrix-facebook#50]
I noticed the Dockerfile contains several python packages that aren't listed in the requirements.txt file. In particular: pillow, beautifulsoup4, yaml, idna, and future. I had all of these on my system already due to matrix-synapse.

**Comment by tulir** [comment]
I only list direct dependencies in requirements.txt. Some indirect dependencies can be found in the dockerfile since I prefer using distro packages to speeds up building the image. The difference is especially noticeable for packages that have native/C deps, which would have to be recompiled if not using distro packages
