### ISSUE TITLE
MQTT disconnected

### ISSUE THREAD

**Issue by wvffle** [tulir/mautrix-facebook#67]
I've been disconnected from MQTT just yesterday on build 85ed247. The bot sent me a dm: 
![image](https://user-images.githubusercontent.com/13330620/84364613-d3e00a80-abbf-11ea-9411-eb0b4431f376.png)

And the logs are following:
![image](https://user-images.githubusercontent.com/13330620/84365971-bf047680-abc1-11ea-8940-6341b495617c.png)

That couldn't be a machine connection loss as other services (synapse, mautrix-telegram, riot, etc.) worked well.

I thought that this may be connected with https://github.com/tulir/mautrix-facebook/issues/45#issuecomment-636523590 but as I had a notification that I'm disconnected I think that this should be another issue

**Comment by tulir** [comment]
You can try enabling [`bridge`→`refresh_on_connection_fail`](https://github.com/tulir/mautrix-facebook/blob/v0.1.0-rc3/mautrix_facebook/example-config.yaml#L159-L161), but other than that the bridge can't do anything if facebook doesn't let it connect (which is why that last message is trying to notify you by using `m.text` instead of `m.notice`)
